#ifndef _FCF_BASIS__BITS__PART_CONTAINER_ACCESS__CONTAINER_POSITION_HPP___
#define _FCF_BASIS__BITS__PART_CONTAINER_ACCESS__CONTAINER_POSITION_HPP___

namespace fcf {

  enum ContainerPosition {
    CP_BEGIN,
    CP_END,
  };

} // fcf namespace

#endif // #ifndef _FCF_BASIS__BITS__PART_CONTAINER_ACCESS__CONTAINER_POSITION_HPP___
