#ifndef _FCF_BASIS__BITS__PART_EXCEPTION__EXCEPTION_PREDEFINITION_HPP___
#define _FCF_BASIS__BITS__PART_EXCEPTION__EXCEPTION_PREDEFINITION_HPP___

namespace fcf{

  class Exception;

} // fcf namespace

#endif // #ifndef _FCF_BASIS__BITS__PART_EXCEPTION__EXCEPTION_PREDEFINITION_HPP___
