#ifndef _FCF_BASIS__BITS__PART_VARIANT__PART_VARIANT_HPP___
#define _FCF_BASIS__BITS__PART_VARIANT__PART_VARIANT_HPP___

#include "Variant.hpp"

#endif // #ifndef _FCF_BASIS__BITS__PART_VARIANT__PART_VARIANT_HPP___
